export const en = {
    translation: {
      heading: 'Co-Farmer',
      Home : "Home",
      crops : "crops",
      producercard : "Register as a producer to sell crops and get connected to producers with required credentials",
      consumercard : "Register as a consumer to buy crops and get connected to producers with required credentials",
      signup : "Sign Up",
      signin : "Sign In",
      producer : "Producer",
      email : "Email Address",
      password : "Password",
      fullname : "Full Name",
      contactnumber : "Contact Number",
      address : "Local/Permanent Address",
      role : "Role",
      consumer : "Consumer",
      about : "About",
      contact : "Contact",
      forgotpass : "Forgot Password",
      nocrops : "No Crops",
      subscribe : "Subscribe",
      delete : "Delete",
      contactme : "Contact Me",
      location : "Location",
      quantity : "Quantity",
      price  : "Price",
      addcrop : "Add Crop",
      selectcrop : "Select Crop",
      ageofcrop : "Age of Crop?",
      uploadcrop : "Upload Crop Img/Vid.",
      add : "ADD"
    },
  }