export const hi = {
    translation: {
        heading: 'Co-Farmer',
        Home : "होम",
        Ordernow : "अभी ऑर्डर करें",
        crops :"फसलें खरीदें",
        producercard : "फसलों को बेचने के लिए एक प्रोड्यूसर के रूप में पंजीकृत करें और आवश्यक योग्यताओं के साथ प्रोड्यूसरों से जुड़ें",
        consumercard : "फसलों को खरीदने के लिए एक कंस्यूमर के रूप में पंजीकृत करें और आवश्यक योग्यताओं के साथ प्रोड्यूसरों से जुड़ें",
        signup : "साइन अप करें",
        signin : "साइन इन करें",
        producer : "प्रोड्यूसर",
        email : "ईमेल पता",
        password : "पासवर्ड",
        fullname : "पूरा नाम",
        contactnumber : "संपर्क नंबर",
        address : "स्थानीय / स्थाई पता",
        role : "भूमिका",
        consumer : "उपभोक्ता",
        about : "के बारे में",
        contact : "संपर्क करें",
        forgotpass : "पासवर्ड भूल गए",
        nocrops : "कोई फसल नहीं",
        subscribe : "सदस्यता लें",
        delete : "हटाएं",
        contactme : "मुझसे संपर्क करें",
        location : "स्थान",
        quantity : "मात्रा",
        price  : "मूल्य",
        addcrop : "फसल जोड़ें",
        selectcrop : "फसल का चयन करें",
        ageofcrop : "फसल की उम्र?",
        uploadcrop : "फसल इमेज / वीडियो अपलोड करें",
        add : "जोड़ें"
    }
}